config/routes.rb
Rails.application.routes.draw do
  root to: "translations#home"

  resources :translations, only: %i[create edit update destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/translation.rb
class Translation < ApplicationRecord


  validates :content, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  def home
    @translation = Translation.new
    @translations = Translation.all

  end

  def create
    input_content = params[:translation][:content]
    output_content = input_content.split(" ")
    # raise
    output_content.map! do |element|
      # if element.chars.count <= 3
        # element.gsub(element[0], "<strong>#{element[0]}</strong>")
        # else
        element.gsub(element.first(element.chars.count.to_f.fdiv(2).round), "<strong>#{element.first(element.chars.count.to_f.fdiv(2).round)}</strong>")
        # end
      end

    @translation = Translation.new
    @translation.content = output_content.join(" ")
    if @translation.save
      redirect_to root_path
    else
      render :home, alert: "it didn't work"
    end


    # >> "hello".gsub('hello'.first(3),'<strong>nana')
    # Try to add if else

    # En fait ça n'a pas l'air de fonctionner sur le double array de lettre, en .map ou .each
    # Je vais essayer de spliter au bon endroit et que ce soit en sub-words


    # Penser à enregistrer avec redirection vers une nouvelle page
    # A voir si après j'ai envie de tester la création avec juste une modale et du JS

  end

  def edit
    @translation = Translation.find(params[:id])
  end

  def update
    @translation = Translation.find(params[:id])
    # Penser à enregistrer
    # @translation.update(translation_params)
    # redirect_to
  end

  def destroy
    @translation = Translation.find(params[:id])
    @translation.destroy
    # redirect_to xxxxx, status: :see_other

  end

  private

  def translation_params
    params.require(:translation).permit(:content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBionicReading</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/translations/create.html.erb
<h1>Translations#create</h1>
<p>Find me in app/views/translations/create.html.erb</p>

app/views/translations/destroy.html.erb
<h1>Translations#destroy</h1>
<p>Find me in app/views/translations/destroy.html.erb</p>

app/views/translations/edit.html.erb
<h1>Translations#edit</h1>
<p>Find me in app/views/translations/edit.html.erb</p>

app/views/translations/home.html.erb
<div class="container-global bg-black" data-controller="form" data-form-target="window">

  <div id="translation_content" class="d-none" data-form-target="result">

  </div>

  <br>
  <div class="d-flex justify-content-around">
    <p class="btn btn-outline-light rounded-pill d-none" data-form-target="change" data-action="click->form#changeText">
      <i class="fa-solid fa-pencil"></i> Change the original text
    </p>

    <button data-action="click->form#reloadPage" class="btn btn-outline-light rounded-pill d-none" data-form-target="change">
      <i class="fa-solid fa-plus"></i> New translation
    </button>
  </div>

    <br><br>


  <%= simple_form_for @translation, url: translations_path, html: {data: {
    form_target: "formulaire",
    action: "submit->form#display"}} do |f| %>
    <%= f.input :content,
                as: :text,
                label: "Text input:",
                label_html: {
                  style: "color: white"
                },
                required: false,
                placeholder: "Enter here the text that you want to transform into bionic reading",
                input_html: {
                  class: "bg-white",
                  # style: "border-radius: 10px",
                  data: {form_target: "input"}}%>
    <%= f.submit "Apply Bionic Reading to my text",
                  class: "btn btn-light"
                  # ,data: {action: "click->form#display"}
    %>
  <% end %>


  <br><br>

  <p><em>To try again with another text, edit directly your text in the text area or click below:
  <button data-action="click->form#reloadPage" class="btn btn-primary rounded-pill">New translation</button>

  <%# <ul data-form-target="list">
  <li>Oui</li>
  <li>Ouiiii</li>
  <li>OUIII</li>
  </ul> %>
</div>


<%# <p><strong>oui</strong></p> %>

  <%#= @translation.content %>
  <% @translations&.last(2).each do |translation|  %>
    <%#= translation.content.split(" ").first(5).join(" ") %>
    <%= translation.id %> - <%= translation.content.html_safe %>
  <% end %>

app/views/translations/update.html.erb
<h1>Translations#update</h1>
<p>Find me in app/views/translations/update.html.erb</p>